# TypedDict → Defines a dictionary with fixed keys and types.
# Annotated → Adds extra metadata to a type (without changing the type iteself)
# Annotated[ActualType, Metadata] => age: Annotated[int, "Age must be positive"]
 
from typing import TypedDict, Annotated, Literal

# BaseMessage represents chat messages (Human, AI, System).
from langchain_core.messages import BaseMessage

# Add_messages is a reducer, appends new messages to the existing chat history instead of replacing it.
from langgraph.graph import add_messages

class GraphState(TypedDict):

    # Stores the raw user's current question.
    query: str

    # To store routing direct for general question no rag, and retrieve for questions from rag
    route: Literal["direct", "retrieve"]

    # Stores retrieved document chunks from pgvector.
    documents: list[dict]

    # Stores the first answer generated by the Generator Agent.
    draft_answer: str

    # Stores the final reviewed answer after citation. 
    final_answer: str

    # Stores citation information (which chunks/sources were used).
    # Python was created in 1991.

    # Source:
    # - Python_Notes.pdf, Page 12
    citations: list[dict]


    # Annotated tells LangGraph to use add_messages() when updating this key instead of replacing it
    # Stores conversation history
    messages: Annotated[list[BaseMessage], add_messages]


